"""initial_migration

Revision ID: da7367e01cd7
Revises: 
Create Date: 2025-09-23 09:57:53.673066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da7367e01cd7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entidad', sa.String(length=64), nullable=False),
    sa.Column('entidad_id', sa.BigInteger(), nullable=False),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=False),
    sa.Column('detalle', sa.JSON(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nit', sa.String(length=64), nullable=False),
    sa.Column('razon_social', sa.String(length=255), nullable=False),
    sa.Column('contacto_email', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nit')
    )
    op.create_table('proveedores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nit', sa.String(length=64), nullable=False),
    sa.Column('razon_social', sa.String(length=255), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('contacto_email', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nit')
    )
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('responsables',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('facturas',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('numero_factura', sa.String(length=50), nullable=False),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('cliente_id', sa.BigInteger(), nullable=True),
    sa.Column('proveedor_id', sa.BigInteger(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('iva', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('moneda', sa.String(length=10), server_default='COP', nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'en_revision', 'aprobada', 'rechazada', 'aprobada_auto', name='estadofactura'), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('observaciones', sa.String(length=2048), nullable=True),
    sa.Column('cufe', sa.String(length=100), nullable=False),
    sa.Column('total_a_pagar', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('responsable_id', sa.BigInteger(), nullable=True),
    sa.Column('aprobada_automaticamente', sa.Boolean(), nullable=True),
    sa.Column('creado_por', sa.String(length=100), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['responsable_id'], ['responsables.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cufe'),
    sa.UniqueConstraint('numero_factura', 'proveedor_id', name='uix_num_prov')
    )
    op.create_table('responsable_proveedor',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('responsable_id', sa.BigInteger(), nullable=False),
    sa.Column('proveedor_id', sa.BigInteger(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsable_id'], ['responsables.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('responsable_id', 'proveedor_id', name='uix_resp_prov')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responsable_proveedor')
    op.drop_table('facturas')
    op.drop_table('responsables')
    op.drop_table('roles')
    op.drop_table('proveedores')
    op.drop_table('clientes')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
